notes2 = {
    '1' : 'A0',
    '2' : 'B0',
    '3' : 'C1',
    '4' : 'D1',
    '5' : 'E1',
    '6' : 'F1',
    '7' : 'G1',
    '8' : 'A1',
    '9' : 'B1',
    '10' : 'C2',
    '11' : 'D2',
    '12' : 'E2',
    '13' : 'F2',
    '14' : 'G2',
    '15' : 'A2',
    '16' : 'B2',
    '17' : 'C3',
    '18' : 'D3',
    '19' : 'E3',
    '20' : 'F3',
    '21' : 'G3',
    '22' : 'A3',
    '23' : 'B3',
    '24' : 'C4',
    '25' : 'D4',
    '26' : 'E4',
    '27' : 'F4',
    '28' : 'G4',
    '29' : 'A4',
    '30' : 'B4',
    '31' : 'C5',
    '32' : 'D5',
    '33' : 'E5',
    '34' : 'F5',
    '35' : 'G5',
    '36' : 'A5',
    '37' : 'B5',
    '38' : 'C6',
    '39' : 'D6',
    '40' : 'E6',
    '41' : 'F6',
    '42' : 'G6',
    '43' : 'A6',
    '44' : 'B6',
    '45' : 'C7',
    '46' : 'D7',
    '47' : 'E7',
    '48' : 'F7',
    '49' : 'G7',
    '50' : 'A7',
    '51' : 'B7',
    '52' : 'C8',
}
notes = {
    'A0' : 'A0.wav',
    'B0' : 'B0.wav',
    'C1' : 'C1.wav',
    'D1' : 'D1.wav',
    'E1' : 'E1.wav',
    'F1' : 'F1.wav',
    'G1' : 'G1.wav',
    'A1' : 'A1.wav',
    'B1' : 'B1.wav',
    'C2' : 'C2.wav',
    'D2' : 'D2.wav',
    'E2' : 'E2.wav',
    'F2' : 'F2.wav',
    'G2' : 'G2.wav',
    'A2' : 'A2.wav',
    'B2' : 'B2.wav',
    'C3' : 'C3.wav',
    'D3' : 'D3.wav',
    'E3' : 'E3.wav',
    'F3' : 'F3.wav',
    'G3' : 'G3.wav',
    'A3' : 'A3.wav',
    'B3' : 'B3.wav',
    'C4' : 'C4.wav',
    'D4' : 'D4.wav',
    'E4' : 'E4.wav',
    'F4' : 'F4.wav',
    'G4' : 'G4.wav',
    'A4' : 'A4.wav',
    'B4' : 'B4.wav',
    'C5' : 'C5.wav',
    'D5' : 'D5.wav',
    'E5' : 'E5.wav',
    'F5' : 'F5.wav',
    'G5' : 'G5.wav',
    'A5' : 'A5.wav',
    'B5' : 'B5.wav',
    'C6' : 'C6.wav',
    'D6' : 'D6.wav',
    'E6' : 'E6.wav',
    'F6' : 'F6.wav',
    'G6' : 'G6.wav',
    'A6' : 'A6.wav',
    'B6' : 'B6.wav',
    'C7' : 'C7.wav',
    'D7' : 'D7.wav',
    'E7' : 'E7.wav',
    'F7' : 'F7.wav',
    'G7' : 'G7.wav',
    'A7' : 'A7.wav',
    'B7' : 'B7.wav',
    'C8' : 'C8.wav',
}
list_notes = [
              'A0',
              'B0',
              'C1',
              'D1',
              'E1',
              'F1',
              'G1',
              'A1',
              'B1',
              'C2',
              'D2',
              'E2',
              'F2',
              'G2',
              'A2',
              'B2',
              'C3',
              'D3',
              'E3',
              'F3',
              'G3',
              'A3',
              'B3',
              'C4',
              'D4',
              'E4',
              'F4',
              'G4',
              'A4',
              'B4',
              'C5',
              'D5',
              'E5',
              'F5',
              'G5',
              'A5',
              'B5',
              'C6',
              'D6',
              'E6',
              'F6',
              'G6',
              'A6',
              'B6',
              'C7',
              'D7',
              'E7',
              'F7',
              'G7',
              'A7',
              'B7',
              'C8'
]
notes3 = {
    'A0' : 'piano/A0.wav',
    'B0' : 'piano/B0.wav',
    'C1' : 'piano/C1.wav',
    'D1' : 'piano/D1.wav',
    'E1' : 'piano/E1.wav',
    'F1' : 'piano/F1.wav',
    'G1' : 'piano/G1.wav',
    'A1' : 'piano/A1.wav',
    'B1' : 'piano/B1.wav',
    'C2' : 'piano/C2.wav',
    'D2' : 'piano/D2.wav',
    'E2' : 'piano/E2.wav',
    'F2' : 'piano/F2.wav',
    'G2' : 'piano/G2.wav',
    'A2' : 'piano/A2.wav',
    'B2' : 'piano/B2.wav',
    'C3' : 'piano/C3.wav',
    'D3' : 'piano/D3.wav',
    'E3' : 'piano/E3.wav',
    'F3' : 'piano/F3.wav',
    'G3' : 'piano/G3.wav',
    'A3' : 'piano/A3.wav',
    'B3' : 'piano/B3.wav',
    'C4' : 'piano/C4.wav',
    'D4' : 'piano/D4.wav',
    'E4' : 'piano/E4.wav',
    'F4' : 'piano/F4.wav',
    'G4' : 'piano/G4.wav',
    'A4' : 'piano/A4.wav',
    'B4' : 'piano/B4.wav',
    'C5' : 'piano/C5.wav',
    'D5' : 'piano/D5.wav',
    'E5' : 'piano/E5.wav',
    'F5' : 'piano/F5.wav',
    'G5' : 'piano/G5.wav',
    'A5' : 'piano/A5.wav',
    'B5' : 'piano/B5.wav',
    'C6' : 'piano/C6.wav',
    'D6' : 'piano/D6.wav',
    'E6' : 'piano/E6.wav',
    'F6' : 'piano/F6.wav',
    'G6' : 'piano/G6.wav',
    'A6' : 'piano/A6.wav',
    'B6' : 'piano/B6.wav',
    'C7' : 'piano/C7.wav',
    'D7' : 'piano/D7.wav',
    'E7' : 'piano/E7.wav',
    'F7' : 'piano/F7.wav',
    'G7' : 'piano/G7.wav',
    'A7' : 'piano/A7.wav',
    'B7' : 'piano/B7.wav',
    'C8' : 'piano/C8.wav'
}
notes2_guitar = {
    '1' : 'C1',
    '2' : 'D1',
    '3' : 'E1',
    '4' : 'F1',
    '5' : 'G1',
    '6' : 'A1',
    '7' : 'B1',
    '8' : 'D3',
    '9' : 'G3',
    '10' : 'C4',
    '11' : 'F4',
    '12' : 'A4',
    '13' : 'B4',
    '14' : 'C5',
    '15' : 'E5',
    '16' : 'A5',
    '17' : 'B5',
    '18' : 'D6',
    '19' : 'E6',
    '20' : 'F6',
    '21' : 'G6',
    '22' : 'F#1',
    '23' : 'G#1',
    '24' : 'A#1',
    '25' : 'C#1',
    '26' : 'D#1',
    '27' : 'E11',
    '28' : 'D#2',
    '29' : 'G#3',
    '30' : 'C#4',
    '31' : 'D#4',
    '32' : 'F#4',
    '33' : 'A#4',
    '34' : 'C#5',
    '35' : 'A#5',
    '36' : 'F#6',
    '37' : 'G#6',
}
notes3_guitar = {
    'C1': 'C1.wav',
    'D1': 'D1.wav',
    'E1': 'E1.wav',
    'F1': 'F1.wav',
    'G1': 'G1.wav',
    'A1': 'A1.wav',
    'B1': 'B1.wav',
    'D3': 'D3.wav',
    'G3': 'G3.wav',
    'C4': 'C4.wav',
    'F4': 'F4.wav',
    'A4': 'A4.wav',
    'B4': 'B4.wav',
    'C5': 'C5.wav',
    'E5': 'E5.wav',
    'A5': 'A5.wav',
    'B5': 'B5.wav',
    'D6': 'D6.wav',
    'E6': 'E6.wav',
    'F6': 'F6.wav',
    'G6': 'G6.wav',
    'F#1': 'F#1.wav',
    'G#1': 'G#1.wav',
    'A#1': 'A#1.wav',
    'C#1': 'C#1.wav',
    'D#1': 'D#1.wav',
    'E11': 'E11.wav',
    'D#2': 'D#2.wav',
    'G#3': 'G#3.wav',
    'C#4': 'C#4.wav',
    'D#4': 'D#4.wav',
    'F#4': 'F#4.wav',
    'A#4': 'A#4.wav',
    'C#5': 'C#5.wav',
    'A#5': 'A#5.wav',
    'F#6': 'F#6.wav',
    'G#6': 'G#6.wav'
}

C = ['C6', 'C5', 'C4', 'C3', 'C2', 'C1']
D = ['D6', 'D5', 'D4', 'D3', 'D2', 'D1', 'D44']
E = ['E6', 'E5', 'E4', 'E3', 'E2', 'E1', 'E66', 'E11']
F = ['F6', 'F5', 'F4', 'F3', 'F2', 'F1']
G = ['G6', 'G5', 'G4', 'G3', 'G2', 'G1', 'G33']
A = ['A6', 'A5', 'A4', 'A3', 'A2', 'A1', 'A55']
B = ['B6', 'B5', 'B4', 'B3', 'B2', 'B1', 'B22']
Cd = ['C#6', 'C#5', 'C#4', 'C#3', 'C#2', 'C#1']
Dd = ['D#6', 'D#5', 'D#4', 'D#3', 'D#2', 'D#1']
Fd = ['F#6', 'F#5', 'F#4', 'F#3', 'F#2', 'F#1']
Gd = ['G#6', 'G#5', 'G#4', 'G#3', 'G#2', 'G#1']
Ad = ['A#6', 'A#5', 'A#4', 'A#3', 'A#2', 'A#1']
sheets = {
    'C6' : C,
    'C5' : C,
    'C4' : C,
    'C3' : C,
    'C2' : C,
    'C1' : C,
    'C#6' : Cd,
    'C#5' : Cd,
    'C#4' : Cd,
    'C#3' : Cd,
    'C#2' : Cd,
    'C#1' : Cd,
    'D6' : D,
    'D5' : D,
    'D4' : D,
    'D3' : D,
    'D2' : D,
    'D1' : D,
    'D44' : D,
    'D#6' : Dd,
    'D#5' : Dd,
    'D#4' : Dd,
    'D#3' : Dd,
    'D#2' : Dd,
    'D#1' : Dd,
    'E6' : E,
    'E5' : E,
    'E4' : E,
    'E3' : E,
    'E2' : E,
    'E1' : E,
    'E66' : E,
    'E11' : E,
    'F6' : F,
    'F5' : F,
    'F4' : F,
    'F3' : F,
    'F2' : F,
    'F1' : F,
    'F#6' : Fd,
    'F#5' : Fd,
    'F#4' : Fd,
    'F#3' : Fd,
    'F#2' : Fd,
    'F#1' : Fd,
    'G6' : G,
    'G5' : G,
    'G4' : G,
    'G3' : G,
    'G2' : G,
    'G1' : G,
    'G33' : G,
    'G#6' : Gd,
    'G#5' : Gd,
    'G#4' : Gd,
    'G#3' : Gd,
    'G#2' : Gd,
    'G#1' : Gd,
    'A6' : A,
    'A5' : A,
    'A4' : A,
    'A3' : A,
    'A2' : A,
    'A1' : A,
    'A55' : A,
    'A#6' : Ad,
    'A#5' : Ad,
    'A#4' : Ad,
    'A#3' : Ad,
    'A#2' : Ad,
    'A#1' : Ad,
    'B6' : B,
    'B5' : B,
    'B4' : B,
    'B3' : B,
    'B2' : B,
    'B1' : B,
    'B22' : B,
}
