# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\info_program.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Info_Window(object):
    def start_info(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("background-color: rgb(129, 71, 68);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.author_label = QtWidgets.QLabel(self.centralwidget)
        self.author_label.setGeometry(QtCore.QRect(80, 80, 261, 51))
        self.author_label.setStyleSheet("font: 32pt \"OCR A Extended\";")
        self.author_label.setObjectName("author_label")
        self.author_text = QtWidgets.QLabel(self.centralwidget)
        self.author_text.setGeometry(QtCore.QRect(280, 80, 411, 51))
        self.author_text.setStyleSheet("font: 32pt \"OCR A Extended\";")
        self.author_text.setObjectName("author_text")
        self.author_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.author_label_2.setGeometry(QtCore.QRect(80, 170, 261, 51))
        self.author_label_2.setStyleSheet("font: 32pt \"OCR A Extended\";")
        self.author_label_2.setObjectName("author_label_2")
        self.author_text_2 = QtWidgets.QLabel(self.centralwidget)
        self.author_text_2.setGeometry(QtCore.QRect(320, 170, 411, 51))
        self.author_text_2.setStyleSheet("font: 32pt \"OCR A Extended\";")
        self.author_text_2.setObjectName("author_text_2")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.back_btn.setStyleSheet("font: 16pt \"OCR A Extended\";")
        self.back_btn.setFlat(True)
        self.back_btn.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Information"))
        self.author_label.setText(_translate("MainWindow", "Author:"))
        self.author_text.setText(_translate("MainWindow", "Sergey Grishin"))
        self.author_label_2.setText(_translate("MainWindow", "Version:"))
        self.author_text_2.setText(_translate("MainWindow", "1.0 Beta"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
