from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pianoWindow(object):

    def startpianoWindow(self, pianoWindow):
        pianoWindow.setObjectName("pianoWindow")
        pianoWindow.resize(1280, 720)
        pianoWindow.setMinimumSize(QtCore.QSize(1280, 720))
        pianoWindow.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("MS Mincho")
        font.setPointSize(24)
        pianoWindow.setFont(font)
        pianoWindow.setStyleSheet("background-color: rgb(60, 179, 113);")
        self.centralwidget = QtWidgets.QWidget(pianoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pic_piano = QtWidgets.QLabel(self.centralwidget)
        self.pic_piano.setGeometry(QtCore.QRect(140, 240, 4981, 221))
        self.pic_piano.setText("")
        self.pic_piano.setPixmap(QtGui.QPixmap("photos/flat_piano.png"))
        self.pic_piano.setObjectName("pic_piano")
        self.C1 = QtWidgets.QPushButton(self.centralwidget)
        self.C1.setGeometry(QtCore.QRect(208, 405, 14, 25))
        self.C1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C1.setObjectName("C1")
        self.D1 = QtWidgets.QPushButton(self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(225, 405, 14, 25))
        self.D1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D1.setObjectName("D1")
        self.E1 = QtWidgets.QPushButton(self.centralwidget)
        self.E1.setGeometry(QtCore.QRect(242, 405, 14, 25))
        self.E1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E1.setObjectName("E1")
        self.F1 = QtWidgets.QPushButton(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(259, 405, 14, 25))
        self.F1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F1.setObjectName("F1")
        self.G1 = QtWidgets.QPushButton(self.centralwidget)
        self.G1.setGeometry(QtCore.QRect(276, 405, 14, 25))
        self.G1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G1.setObjectName("G1")
        self.A1 = QtWidgets.QPushButton(self.centralwidget)
        self.A1.setGeometry(QtCore.QRect(293, 405, 14, 25))
        self.A1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A1.setObjectName("A1")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(311, 405, 14, 25))
        self.B1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B1.setObjectName("B1")
        self.F2 = QtWidgets.QPushButton(self.centralwidget)
        self.F2.setGeometry(QtCore.QRect(380, 405, 14, 25))
        self.F2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F2.setObjectName("F2")
        self.E2 = QtWidgets.QPushButton(self.centralwidget)
        self.E2.setGeometry(QtCore.QRect(364, 405, 14, 25))
        self.E2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E2.setObjectName("E2")
        self.G2 = QtWidgets.QPushButton(self.centralwidget)
        self.G2.setGeometry(QtCore.QRect(398, 405, 14, 25))
        self.G2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G2.setObjectName("G2")
        self.A2 = QtWidgets.QPushButton(self.centralwidget)
        self.A2.setGeometry(QtCore.QRect(415, 405, 14, 25))
        self.A2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A2.setObjectName("A2")
        self.B2 = QtWidgets.QPushButton(self.centralwidget)
        self.B2.setGeometry(QtCore.QRect(432, 405, 14, 25))
        self.B2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B2.setObjectName("B2")
        self.D2 = QtWidgets.QPushButton(self.centralwidget)
        self.D2.setGeometry(QtCore.QRect(346, 405, 14, 25))
        self.D2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D2.setObjectName("D2")
        self.C2 = QtWidgets.QPushButton(self.centralwidget)
        self.C2.setGeometry(QtCore.QRect(329, 405, 14, 25))
        self.C2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C2.setObjectName("C2")
        self.C3 = QtWidgets.QPushButton(self.centralwidget)
        self.C3.setGeometry(QtCore.QRect(450, 405, 14, 25))
        self.C3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C3.setObjectName("C3")
        self.D3 = QtWidgets.QPushButton(self.centralwidget)
        self.D3.setGeometry(QtCore.QRect(467, 405, 14, 25))
        self.D3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D3.setObjectName("D3")
        self.E3 = QtWidgets.QPushButton(self.centralwidget)
        self.E3.setGeometry(QtCore.QRect(483, 405, 14, 25))
        self.E3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E3.setObjectName("E3")
        self.F3 = QtWidgets.QPushButton(self.centralwidget)
        self.F3.setGeometry(QtCore.QRect(500, 405, 14, 25))
        self.F3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F3.setObjectName("F3")
        self.G3 = QtWidgets.QPushButton(self.centralwidget)
        self.G3.setGeometry(QtCore.QRect(518, 405, 14, 25))
        self.G3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G3.setObjectName("G3")
        self.A3 = QtWidgets.QPushButton(self.centralwidget)
        self.A3.setGeometry(QtCore.QRect(535, 405, 14, 25))
        self.A3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A3.setObjectName("A3")
        self.B3 = QtWidgets.QPushButton(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(553, 405, 14, 25))
        self.B3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B3.setObjectName("B3")
        self.C4 = QtWidgets.QPushButton(self.centralwidget)
        self.C4.setGeometry(QtCore.QRect(570, 405, 14, 25))
        self.C4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C4.setObjectName("C4")
        self.D4 = QtWidgets.QPushButton(self.centralwidget)
        self.D4.setGeometry(QtCore.QRect(588, 405, 14, 25))
        self.D4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D4.setObjectName("D4")
        self.E4 = QtWidgets.QPushButton(self.centralwidget)
        self.E4.setGeometry(QtCore.QRect(604, 405, 14, 25))
        self.E4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E4.setObjectName("E4")
        self.F4 = QtWidgets.QPushButton(self.centralwidget)
        self.F4.setGeometry(QtCore.QRect(622, 405, 14, 25))
        self.F4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F4.setObjectName("F4")
        self.G4 = QtWidgets.QPushButton(self.centralwidget)
        self.G4.setGeometry(QtCore.QRect(640, 405, 14, 25))
        self.G4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G4.setObjectName("G4")
        self.A4 = QtWidgets.QPushButton(self.centralwidget)
        self.A4.setGeometry(QtCore.QRect(657, 405, 14, 25))
        self.A4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A4.setObjectName("A4")
        self.B4 = QtWidgets.QPushButton(self.centralwidget)
        self.B4.setGeometry(QtCore.QRect(674, 405, 14, 25))
        self.B4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B4.setObjectName("B4")
        self.C5 = QtWidgets.QPushButton(self.centralwidget)
        self.C5.setGeometry(QtCore.QRect(692, 405, 14, 25))
        self.C5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C5.setObjectName("C5")
        self.D5 = QtWidgets.QPushButton(self.centralwidget)
        self.D5.setGeometry(QtCore.QRect(710, 405, 14, 25))
        self.D5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D5.setObjectName("D5")
        self.E5 = QtWidgets.QPushButton(self.centralwidget)
        self.E5.setGeometry(QtCore.QRect(726, 405, 14, 25))
        self.E5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E5.setObjectName("E5")
        self.F5 = QtWidgets.QPushButton(self.centralwidget)
        self.F5.setGeometry(QtCore.QRect(743, 405, 14, 25))
        self.F5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F5.setObjectName("F5")
        self.G5 = QtWidgets.QPushButton(self.centralwidget)
        self.G5.setGeometry(QtCore.QRect(760, 405, 14, 25))
        self.G5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G5.setObjectName("G5")
        self.A5 = QtWidgets.QPushButton(self.centralwidget)
        self.A5.setGeometry(QtCore.QRect(778, 405, 14, 25))
        self.A5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A5.setObjectName("A5")
        self.B5 = QtWidgets.QPushButton(self.centralwidget)
        self.B5.setGeometry(QtCore.QRect(796, 405, 14, 25))
        self.B5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B5.setObjectName("B5")
        self.C6 = QtWidgets.QPushButton(self.centralwidget)
        self.C6.setGeometry(QtCore.QRect(812, 405, 14, 25))
        self.C6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C6.setObjectName("C6")
        self.D6 = QtWidgets.QPushButton(self.centralwidget)
        self.D6.setGeometry(QtCore.QRect(830, 405, 14, 25))
        self.D6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D6.setObjectName("D6")
        self.E6 = QtWidgets.QPushButton(self.centralwidget)
        self.E6.setGeometry(QtCore.QRect(847, 405, 14, 25))
        self.E6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E6.setObjectName("E6")
        self.F6 = QtWidgets.QPushButton(self.centralwidget)
        self.F6.setGeometry(QtCore.QRect(864, 405, 14, 25))
        self.F6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F6.setObjectName("F6")
        self.G6 = QtWidgets.QPushButton(self.centralwidget)
        self.G6.setGeometry(QtCore.QRect(881, 405, 14, 25))
        self.G6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G6.setObjectName("G6")
        self.A6 = QtWidgets.QPushButton(self.centralwidget)
        self.A6.setGeometry(QtCore.QRect(899, 405, 14, 25))
        self.A6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A6.setObjectName("A6")
        self.B6 = QtWidgets.QPushButton(self.centralwidget)
        self.B6.setGeometry(QtCore.QRect(916, 405, 14, 25))
        self.B6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B6.setObjectName("B6")
        self.C7 = QtWidgets.QPushButton(self.centralwidget)
        self.C7.setGeometry(QtCore.QRect(933, 405, 14, 25))
        self.C7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C7.setObjectName("C7")
        self.D7 = QtWidgets.QPushButton(self.centralwidget)
        self.D7.setGeometry(QtCore.QRect(951, 405, 14, 25))
        self.D7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D7.setObjectName("D7")
        self.E7 = QtWidgets.QPushButton(self.centralwidget)
        self.E7.setGeometry(QtCore.QRect(968, 405, 14, 25))
        self.E7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.E7.setObjectName("E7")
        self.F7 = QtWidgets.QPushButton(self.centralwidget)
        self.F7.setGeometry(QtCore.QRect(985, 405, 14, 25))
        self.F7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.F7.setObjectName("F7")
        self.G7 = QtWidgets.QPushButton(self.centralwidget)
        self.G7.setGeometry(QtCore.QRect(1002, 405, 14, 25))
        self.G7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.G7.setObjectName("G7")
        self.A7 = QtWidgets.QPushButton(self.centralwidget)
        self.A7.setGeometry(QtCore.QRect(1020, 405, 14, 25))
        self.A7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A7.setObjectName("A7")
        self.B7 = QtWidgets.QPushButton(self.centralwidget)
        self.B7.setGeometry(QtCore.QRect(1037, 405, 14, 25))
        self.B7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B7.setObjectName("B7")
        self.C8 = QtWidgets.QPushButton(self.centralwidget)
        self.C8.setGeometry(QtCore.QRect(1053, 405, 14, 25))
        self.C8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.C8.setObjectName("C8")
        self.A0 = QtWidgets.QPushButton(self.centralwidget)
        self.A0.setGeometry(QtCore.QRect(172, 405, 14, 25))
        self.A0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.A0.setObjectName("A0")
        self.B0 = QtWidgets.QPushButton(self.centralwidget)
        self.B0.setGeometry(QtCore.QRect(190, 405, 14, 25))
        self.B0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B0.setObjectName("B0")
        self.back_to_menu_pic = QtWidgets.QLabel(self.centralwidget)
        self.back_to_menu_pic.setGeometry(QtCore.QRect(20, 30, 51, 51))
        self.back_to_menu_pic.setText("")
        self.back_to_menu_pic.setPixmap(QtGui.QPixmap("../photos/back.png"))
        self.back_to_menu_pic.setObjectName("back_to_menu_pic")
        self.btn_back_to_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back_to_menu.setGeometry(QtCore.QRect(20, 30, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setFamily('OCR A Extended')
        self.btn_back_to_menu.setFont(font)
        self.btn_back_to_menu.setText("Back")
        self.btn_back_to_menu.setFlat(True)
        self.btn_back_to_menu.setObjectName("btn_back_to_menu")
        self.score = 0
        self.replay_note = QtWidgets.QPushButton(self.centralwidget)
        self.replay_note.setGeometry(QtCore.QRect(500, 480, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setFamily('OCR A Extended')
        self.replay_note.setFont(font)
        self.replay_note.setStyleSheet("background-color: rgb(60, 179, 113);")
        self.replay_note.setObjectName("replay_note")
        self.replay_note.setText('replay')
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setGeometry(QtCore.QRect(640, 480, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setFamily('OCR A Extended')
        self.next_btn.setFont(font)
        self.next_btn.setObjectName("next")
        self.line_sheet = QtWidgets.QLineEdit(self.centralwidget)
        self.line_sheet.setGeometry(QtCore.QRect(500, 520, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setFamily('OCR A Extended')
        self.line_sheet.setFont(font)
        self.line_sheet.setStyleSheet("background-color: rgb(60, 179, 113);")
        self.line_sheet.setAlignment(QtCore.Qt.AlignCenter)
        self.line_sheet.setObjectName("line_sheet")
        self.text_score = QtWidgets.QLabel(self.centralwidget)
        self.text_score.setGeometry(QtCore.QRect(500, 590, 259, 78))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.text_score.setFont(font)
        self.text_score.setObjectName("text_score")
        pianoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(pianoWindow)
        QtCore.QMetaObject.connectSlotsByName(pianoWindow)

    def retranslateUi(self, pianoWindow):
        _translate = QtCore.QCoreApplication.translate
        pianoWindow.setWindowTitle(_translate("pianoWindow", "Test your ear"))
        self.C1.setText(_translate("pianoWindow", "C1"))
        self.D1.setText(_translate("pianoWindow", "D1"))
        self.E1.setText(_translate("pianoWindow", "E1"))
        self.F1.setText(_translate("pianoWindow", "F1"))
        self.G1.setText(_translate("pianoWindow", "G1"))
        self.A1.setText(_translate("pianoWindow", "A1"))
        self.B1.setText(_translate("pianoWindow", "B1"))
        self.F2.setText(_translate("pianoWindow", "F2"))
        self.E2.setText(_translate("pianoWindow", "E2"))
        self.G2.setText(_translate("pianoWindow", "G2"))
        self.A2.setText(_translate("pianoWindow", "A2"))
        self.B2.setText(_translate("pianoWindow", "B2"))
        self.D2.setText(_translate("pianoWindow", "D2"))
        self.C2.setText(_translate("pianoWindow", "C2"))
        self.C3.setText(_translate("pianoWindow", "C3"))
        self.D3.setText(_translate("pianoWindow", "D3"))
        self.E3.setText(_translate("pianoWindow", "E3"))
        self.F3.setText(_translate("pianoWindow", "F3"))
        self.G3.setText(_translate("pianoWindow", "G3"))
        self.A3.setText(_translate("pianoWindow", "A3"))
        self.B3.setText(_translate("pianoWindow", "B3"))
        self.C4.setText(_translate("pianoWindow", "C4"))
        self.D4.setText(_translate("pianoWindow", "D4"))
        self.E4.setText(_translate("pianoWindow", "E4"))
        self.F4.setText(_translate("pianoWindow", "F4"))
        self.G4.setText(_translate("pianoWindow", "G4"))
        self.A4.setText(_translate("pianoWindow", "A4"))
        self.B4.setText(_translate("pianoWindow", "B4"))
        self.C5.setText(_translate("pianoWindow", "C5"))
        self.D5.setText(_translate("pianoWindow", "D5"))
        self.E5.setText(_translate("pianoWindow", "E5"))
        self.F5.setText(_translate("pianoWindow", "F5"))
        self.G5.setText(_translate("pianoWindow", "G5"))
        self.A5.setText(_translate("pianoWindow", "A5"))
        self.B5.setText(_translate("pianoWindow", "B5"))
        self.C6.setText(_translate("pianoWindow", "C6"))
        self.D6.setText(_translate("pianoWindow", "D6"))
        self.E6.setText(_translate("pianoWindow", "E6"))
        self.F6.setText(_translate("pianoWindow", "F6"))
        self.G6.setText(_translate("pianoWindow", "G6"))
        self.A6.setText(_translate("pianoWindow", "A6"))
        self.B6.setText(_translate("pianoWindow", "B6"))
        self.C7.setText(_translate("pianoWindow", "C7"))
        self.D7.setText(_translate("pianoWindow", "D7"))
        self.E7.setText(_translate("pianoWindow", "E7"))
        self.F7.setText(_translate("pianoWindow", "F7"))
        self.G7.setText(_translate("pianoWindow", "G7"))
        self.A7.setText(_translate("pianoWindow", "A7"))
        self.B7.setText(_translate("pianoWindow", "B7"))
        self.C8.setText(_translate("pianoWindow", "C8"))
        self.A0.setText(_translate("pianoWindow", "A0"))
        self.B0.setText(_translate("pianoWindow", "B0"))
        self.next_btn.setText(_translate("pianoWindow", "next"))
        self.text_score.setText(_translate("pianoWindow", f"Score: {self.score}"))