from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox     #должно показываться окно в случае проигрыша и


class Ui_MainWindow():

    def startWindow(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sheet.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 102);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_text = QtWidgets.QLabel(self.centralwidget)
        self.start_text.setGeometry(QtCore.QRect(470, 250, 721, 81))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(40)
        self.start_text.setFont(font)
        self.start_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.start_text.setObjectName("starttext")
        self.btn_playpiano = QtWidgets.QPushButton(self.centralwidget)
        self.btn_playpiano.setGeometry(QtCore.QRect(440, 390, 215, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.btn_playpiano.setFont(font)
        self.btn_playpiano.setObjectName("playpiano")
        self.btn_playguitar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_playguitar.setGeometry(QtCore.QRect(740, 390, 215, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.btn_playguitar.setFont(font)
        self.btn_playguitar.setObjectName("playguitar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.recomend = QtWidgets.QLabel(self.centralwidget)
        self.recomend.setGeometry(20, 0, 400, 200)
        font = QtGui.QFont()
        font.setFamily('OCR A Extended')
        font.setPointSize(20)
        self.recomend.setFont(font)
        self.recomend.setObjectName('recomendation')
        self.recomend.setText('recommended\nto play\nwith headphones')
        self.info = QtWidgets.QPushButton(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(10, 10, 100, 40))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(24)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.set_text_for_winmain(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def set_text_for_winmain(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test your ear"))
        self.start_text.setText(_translate("MainWindow", "Test your ear"))
        self.btn_playpiano.setText(_translate("MainWindow", "play piano"))
        self.btn_playguitar.setText(_translate("MainWindow", "play guitar"))
        self.info.setText(_translate("MainWindow", "info"))
